spring.datasource.url=jdbc:postgresql://localhost:5432/ledger_db
spring.datasource.username=ledger_admin
spring.datasource.password=secure_password_123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hiberbate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.sql.init.mode=never

jwt.secret=mySecretKeyWithAtLeast32CharactersLong!
jwt.expiration=86400000
